spring:
  application:
    name: moonwalk

  datasource:
    url: jdbc:mysql://localhost:3306/moonwalk_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  threads:
    virtual:
      enabled: true